name: website_nav_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_proxy: ^1.0.4
  mysql1: ^0.20.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.7
